# 行列

In [6]:
#リストからarrayを生成
import numpy as np

a = np.array([1, 2, 3])

print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
#リストから二次元arrayを生成
import numpy as np
a = np.array(
    [[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
#0～9の要素を持った一次元arrayの生成
import numpy as np
a = np.arange(10)

print(a)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
#0～9の要素を持った一次元arrayを3×3の二次元arrayに変換
import numpy as np
a = np.arange(9)
b = a.reshape( (3, 3) )

print(a)
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
#二次元arrayの要素を一列(1次元)に並べる
import numpy as np

a = np.arange(9).reshape( (3, 3) )
b = a.flatten()

print(b)

[0 1 2 3 4 5 6 7 8]
